Manasa/unlocked edit
cboard-org/cboard-mobile pull request #6
Opened 2021-07-29 14:31 UTC by manasapakala191

Added/Modified :
- Edit tile with colour switching, editable name, and other UI changes
- Delete dialog
- UI change on tiles screen after long press
- Image picker for edit screen
- New Tile/ Board
- Voice recorder and playback

https://user-images.githubusercontent.com/57900828/127508874-250e1478-dc41-4d96-af4b-a4425a135eb3.mp4

2021-07-31 22:18 UTC, tungtrn commented on lib/unlocked/widgets/Tiles.dart
> +                  style: TextStyle(color: Color(0xffC62828)),
This should be put in `Contant.dart` file

2021-07-31 22:22 UTC, tungtrn commented on lib/unlocked/widgets/Tiles.dart
> +                  height: 21.44,
Can we have the length value set relative to `screenSize` like other properties?

2021-07-31 22:24 UTC, tungtrn requested changes
Good jobb @manasapakala191 !

I checked out the screens and it is great! 

I added some minor comments about the constant and the screen size. Also, I merge `Summer2021` into your branch and resolve some conflicts. Please check if your changes are affected.

2021-08-03 23:40 UTC, tungtrn commented on lib/data/data.dart
> +      imageUrl: 'assets/images/empty.png',
I can't find `empty.png` so it causes the error when running

2021-08-03 23:48 UTC, tungtrn requested changes
@manasapakala191  Thank you so much for fixing the last comment:
There are 2 minor issues that I found:
- There isn't a file named `empty.png` in the asset so I could not find it. Did you forget to commit it?
- The image below is a bit different from the design, the color of the tiles should be fully covered
![Screen Shot 2021-08-03 at 7 36 23 PM](https://user-images.githubusercontent.com/59303921/128099946-1aff6295-43e9-47b0-8e49-863f980d5bd9.png)

Also, I added a .gitignore file in the `Summer2021` branch, it would be great if you can pull it to your branch so we don't have unnecessary files

2021-08-17 02:55 UTC, nganphan123 reviewed
Great work Manasa. I just added a small comment.

2021-08-17 02:55 UTC, nganphan123 commented on lib/unlocked/EditTile.dart
> +                        OutlinedButton(
There is a `button` class in shared folder. I think you can try using that

2021-08-17 02:55 UTC, nganphan123 commented on lib/unlocked/EditTile.dart
> +                          style: OutlinedButton.styleFrom(
Same as above

2021-09-09 11:05 UTC, manasapakala191 commented
Updates:

- Select, select-all for edit, delete updated
- Navigation string to folder on the home screen
- Download the voice recording and store offline

Questions:
1. Should the sentence bar be added in the unlocked home screen as well?
2. In the edit/add tile page, do I add a test vocal button for testing the TTS for the tile label?

2021-09-26 03:12 UTC, tungtrn approved these changes
Hi Rukmini,

Thank you so much for fixing the issues and implementing the UI.

The functionalities and the UI looks good on my end. There are some minor places that the UI is overflowed on my screen. I guess it may be because of the fixed padding size and you may want to consider that (Screenshot attached below)
<img width="360" alt="Screen Shot 2021-09-25 at 11 04 43 PM" src="https://user-images.githubusercontent.com/59303921/134792055-b5943356-1216-4e3e-abc4-0c8f2313b191.png">


Since this is not a major issue, you can work on it while you are integrating the API as well so I will approve it for now.

Thank you so much!! 👏👏

Please let me know if you have any questions!

2021-10-09 05:29 UTC, merged